name: CI/CD Pipeline

# ワークフローが実行されるタイミングを定義
on:
  # main ブランチ以外への push 時に実行
  push:
    branches-ignore:
      - main
  # main ブランチへの pull request 作成・更新時に実行
  pull_request:
    branches:
      - main

jobs:
  # テストを実行するジョブ
  test:
    runs-on: ubuntu-latest # ジョブを実行するランナーを指定
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 開発環境のセットアップ (プロジェクトに合わせて変更してください)
      #    例: Node.js プロジェクトの場合
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 使用する Node.js のバージョン
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # または特定のバージョンを指定
      - name: Install dependencies
        run: bun install # bunを使用して依存パッケージをインストール

      #    例: Python プロジェクトの場合
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.10' # 使用する Python のバージョン
      # - name: Install dependencies
      #   run: pip install -r requirements.txt # 依存パッケージのインストール

      # 3. テストの実行 (プロジェクトに合わせて変更してください)
      - name: Run tests
        run: echo "Running tests..." # ここに実際のテストコマンドを記述 (例: npm test, pytest など)

  # Docker イメージをビルドするジョブ
  build:
    runs-on: ubuntu-latest
    # main ブランチへのプルリクエストの場合のみ実行
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    # test ジョブが成功した場合のみ実行
    needs: test
    steps:
      # 1. リポジトリのコードをチェックアウト (プルリクエストのコードを取得)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # プルリクエストの最新のコミットを参照
          ref: ${{ github.event.pull_request.head.sha }}

      # 2. Docker Buildx のセットアップ (より高度なビルド機能を提供)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. (オプション) Docker レジストリへのログイン
      #    ビルドしたイメージを Docker Hub や GitHub Container Registry (GHCR) に
      #    プッシュする場合に必要です。Secrets の設定が必要です。
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Log in to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Docker イメージのビルド
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Dockerfile があるディレクトリのパス
          file: ./Dockerfile # Dockerfile のパス (デフォルトは context/Dockerfile)
          push: false # 今回はビルドのみ実行。レジストリにプッシュする場合は true に設定
          tags: your-image-name:latest # 適切なイメージ名とタグを指定
          # 必要に応じてビルド引数 (build-args) などを追加できます
          # build-args: |
          #   ARG_NAME=value